### ISSUE TITLE
handle_transition update event

### ISSUE THREAD

**Issue by bnns** [ityonemo/state_server#37]
thank you for this library -

I'm currently trying to use `handle_transition/3` in conjunction with `on_state_entry/3` and it seems that the update from the former doesn't show up in the latter. I wanted to have 2 update events, one requiring the other.

I've created a test that shows this behavior in #36

Is this a bug or expected? If it's expected, should I instead split my state into 2?

**Comment by ityonemo** [comment]
cool.  Going to take a look at this now!

**Comment by ityonemo** [comment]
Thanks for bringing this up.  I made a couple of changes to the test to reflect the intent of the system, and I'm going to persist these in the code branch.

Events (including state_entry events) should generally be handled only in one function body (there should be no "double hits").  So if you handle it in one of the clauses the main section of the state_server, it won't fall through to the State module in the :defer statement.  That is part of the reason why I wanted to make the defer statement not look like a def block, so that you don't think of it as a function block.

I'm going to make the documentation on this more clear.  If you have suggestions on how to do this, please feel free to PR into the "bnn-bugfix" branch (sorry I mistyped your user name in the branch) which will be merged in with the next release.

4aa58e6dd201f10b0820a8d6eede6bd6c54f1aae

**Comment by ityonemo** [comment]
also I added a demonstration of how to do a double hit in:

ac5708fdbbcc694e50f4a382cced7f4cd6750686
